### ISSUE TITLE
CSS for Bootstrap

### ISSUE THREAD

**Issue by isaackehle** [imevro/ng-switcher#4]
Hey, it seems that there's not a lot of movement on this project, but I'm making use of it in my work.

Though I'd drop you a css file that can be used for colorizing and sizing the switchers.. 

``` css

.switcher-lg .switch {
    width: 100px !important;
    height: 50px !important;
    border-radius: 25px !important;
}

.switcher-lg .switch-button {
    height: 50px !important;
    width: 50px !important;
    border-radius: 25px !important;
    margin-top: -1px !important;
}

.switcher-lg .switch-left .switch-button {
    left: -1px !important;
}

.switcher-lg .switch-right {
}

.switcher-lg .switch-right .switch-button {
    left: 50px !important;
}

.switcher-default .switch {
    border: 1px solid #eeeeee !important;
}

.switcher-default .switch-button {
    background: white !important;
    border: 1px solid #c0c0c0 !important;
}

.switcher-default .switch-right {
    background: #c0c0c0 !important;
    border-color: #c0c0c0 !important;
}

.switcher-success .switch {
    border: 1px solid #eeeeee !important;
}

.switcher-success .switch-button {
    background: white !important;
    border: 1px solid #2ecc71 !important;
}

.switcher-success .switch-right {
    background: #2ecc71 !important;
    border-color: #2ecc71 !important;
}

.switcher-primary .switch {
    border: 1px solid #eeeeee !important;
}

.switcher-primary .switch-button {
    background: white !important;
    border: 1px solid #337AB7 !important;
}

.switcher-primary .switch-right {
    background: #337AB7 !important;
    border-color: #337AB7 !important;
}

.switcher-info .switch {
    border: 1px solid #eeeeee !important;
}

.switcher-info .switch-button {
    background: white !important;
    border: 1px solid #5BC0DE !important;
}

.switcher-info .switch-right {
    background: #5BC0DE !important;
    border-color: #5BC0DE !important;
}

.switcher-warning .switch {
    border: 1px solid #eeeeee !important;
}

.switcher-warning .switch-button {
    background: white !important;
    border: 1px solid #F0AD4E !important;
}

.switcher-warning .switch-right {
    background: #F0AD4E !important;
    border-color: #F0AD4E !important;
}

.switcher-danger .switch {
    border: 1px solid #eeeeee !important;
}

.switcher-danger .switch-button {
    background: white !important;
    border: 1px solid #D9534F !important;
}

.switcher-danger .switch-right {
    background: #D9534F !important;
    border-color: #D9534F !important;
}

```

Hope that helps...
